#!/usr/bin/env python3
from xml.dom.minidom import parse
document = parse("config.xml")
k1 = float(document.getElementsByTagName("k1")[0].childNodes[0].nodeValue)
mu = float(document.getElementsByTagName("mu")[0].childNodes[0].nodeValue)
volume = mu + 2 * k1
with open("result.xml", "w") as file:
	file.write('''<?xml version="1.0" encoding="utf-8"?>
<MSolve4Korali_output version="1.0">
	<Volume>%.16e</Volume>
	<Timeteps>3</Timeteps>
	<SolutionMsg>Fail</SolutionMsg>
</MSolve4Korali_output>
''' % volume)
