/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

/* Use Nvidia CUDNN backend for Deep Neural Networks (requires CUDA) */
#undef _KORALI_USE_CUDNN

/* Use MPI for distributed memory parallelism */
#define _KORALI_USE_MPI

/* Use MPI4Py for distributed memory parallelism on Python */
#undef _KORALI_USE_MPI4PY

/* Use Intel OndeDNN backend for Deep Neural Networks */
#undef _KORALI_USE_ONEDNN

